<?php

function bbloomer_get_product_ids_by_tags($select,...$tags) {
	$args = func_get_args();
   $all_ids = get_posts( array(
      'post_type' => 'product',
      'numberposts' => -1,
      'post_status' => 'publish',
      'fields' => 'ids',
      'tax_query' => array(
         array(
            'taxonomy' => 'product_tag',
            'field' => 'slug',
            'terms' => $tags,
            'operator' => 'AND',
         )
      ),
   ) );
	echo "<select name='$select'><option value='none'>None</option>";

   foreach ( $all_ids as $id ) {
	   $product = wc_get_product( $id );
	   $name = $product -> get_name();
	   $sku = $product -> get_sku();
	   $price = $product -> get_price();
	   
      echo "<option value='$name' data-product_sku='$sku' data-product-id='$id' data-product-price='$price'>$name (+ $$price/bu)</option>";
   }

	echo "</select>";
}


function iconic_get_product_id_by_sku( $sku = false ) {
 
    global $wpdb;
 
    if( !$sku )
        return null;
 
    $product_id = $wpdb->get_var( $wpdb->prepare( "SELECT post_id FROM $wpdb->postmeta WHERE meta_key='_sku' AND meta_value='%s' LIMIT 1", $sku ) );
 
    if ( $product_id ) {
		$product = wc_get_product( $product_id );
		$name = $product-> get_name();
		$price = $product -> get_price();
		$data = array($product_id,$name,$price);
        return $data;
	}
    return null;
    
}


$PrecedeC_WheatSeed = iconic_get_product_id_by_sku('PrecedeC-WheatSeed');
$PrecedeC_DurumSeed = iconic_get_product_id_by_sku('PrecedeC-DurumSeed');
$PrecedeC_OatSeed = iconic_get_product_id_by_sku('PrecedeC-OatSeed');
$PrecedeC_BarleySeed = iconic_get_product_id_by_sku('PrecedeC-BarleySeed');
$PrecedeC_FlaxSeed = iconic_get_product_id_by_sku('PrecedeC-FlaxSeed');
$PrecedeC_FallRyeSeed = iconic_get_product_id_by_sku('PrecedeC-FallRyeSeed');
$PrecedeC_CanarySeed = iconic_get_product_id_by_sku('PrecedeC-CanarySeed');
$PrecedeP_PeaSeed = iconic_get_product_id_by_sku('PrecedeP-PeaSeed');
$PrecedeP_LentilSeed = iconic_get_product_id_by_sku('PrecedeP-LentilSeed');
$Action5_WheatSeed = iconic_get_product_id_by_sku('Action5-WheatSeed');
$Action5_DurumSeed = iconic_get_product_id_by_sku('Action5-DurumSeed');
$Action5_OatSeed = iconic_get_product_id_by_sku('Action5-OatSeed');
$Action5_BarleySeed = iconic_get_product_id_by_sku('Action5-BarleySeed');
$Action5_FlaxSeed = iconic_get_product_id_by_sku('Action5-FlaxSeed');
$Action5_FallRyeSeed = iconic_get_product_id_by_sku('Action5-FallRyeSeed');
$Action5_CanarySeed = iconic_get_product_id_by_sku('Action5-CanarySeed');
$BioForge_PeaSeed = iconic_get_product_id_by_sku('BioForge-PeaSeed');
$BioForge_LentilSeed = iconic_get_product_id_by_sku('BioForge-LentilSeed');
$PulsePrimer_PeaSeed = iconic_get_product_id_by_sku('PulsePrimer-PeaSeed');
$PulsePrimer_LentilSeed = iconic_get_product_id_by_sku('PulsePrimer-LentilSeed');
$PulsePak_PeaSeed = iconic_get_product_id_by_sku('PulsePak-PeaSeed');
$PulsePak_LentilSeed = iconic_get_product_id_by_sku('PulsePak-LentilSeed');
$PrimerZn_WheatSeed = iconic_get_product_id_by_sku('PrimerZn-WheatSeed');
$PrimerZn_DurumSeed = iconic_get_product_id_by_sku('PrimerZn-DurumSeed');
$PrimerZn_OatSeed = iconic_get_product_id_by_sku('PrimerZn-OatSeed');
$PrimerZn_BarleySeed = iconic_get_product_id_by_sku('PrimerZn-BarleySeed');
$PrimerZn_FlaxSeed = iconic_get_product_id_by_sku('PrimerZn-FlaxSeed');
$PrimerZn_FallRyeSeed = iconic_get_product_id_by_sku('PrimerZn-FallRyeSeed');
$PrimerZn_CanarySeed = iconic_get_product_id_by_sku('PrimerZn-CanarySeed');
$PrimerCu_WheatSeed = iconic_get_product_id_by_sku('PrimerCu-WheatSeed');
$PrimerCu_DurumSeed = iconic_get_product_id_by_sku('PrimerCu-DurumSeed');
$PrimerCu_OatSeed = iconic_get_product_id_by_sku('PrimerCu-OatSeed');
$PrimerCu_BarleySeed = iconic_get_product_id_by_sku('PrimerCu-BarleySeed');
$PrimerCu_FlaxSeed = iconic_get_product_id_by_sku('PrimerCu-FlaxSeed');
$PrimerCu_FallRyeSeed = iconic_get_product_id_by_sku('PrimerCu-FallRyeSeed');
$PrimerCu_CanarySeed = iconic_get_product_id_by_sku('PrimerCu-CanarySeed');
$PrimerMn_WheatSeed = iconic_get_product_id_by_sku('PrimerMn-WheatSeed');
$PrimerMn_DurumSeed = iconic_get_product_id_by_sku('PrimerMn-DurumSeed');
$PrimerMn_OatSeed = iconic_get_product_id_by_sku('PrimerMn-OatSeed');
$PrimerMn_BarleySeed = iconic_get_product_id_by_sku('PrimerMn-BarleySeed');
$PrimerMn_FlaxSeed = iconic_get_product_id_by_sku('PrimerMn-FlaxSeed');
$PrimerMn_FallRyeSeed = iconic_get_product_id_by_sku('PrimerMn-FallRyeSeed');
$PrimerMn_CanarySeed = iconic_get_product_id_by_sku('PrimerMn-CanarySeed');
$TagTeamLCO_PeaSeed = iconic_get_product_id_by_sku('TagTeamLCO-PeaSeed');
$TagTeamLCO_LentilSeed = iconic_get_product_id_by_sku('TagTeamLCO-LentilSeed');
$CellTech_PeaSeed = iconic_get_product_id_by_sku('CellTech-PeaSeed');
$CellTech_LentilSeed = iconic_get_product_id_by_sku('CellTech-LentilSeed');
$Nodulator_PeaSeed = iconic_get_product_id_by_sku('Nodulator-PeaSeed');
$Nodulator_LentilSeed = iconic_get_product_id_by_sku('Nodulator-LentilSeed');
$Accolade_WheatSeed = iconic_get_product_id_by_sku('Accolade-WheatSeed');
$Accolade_DurumSeed = iconic_get_product_id_by_sku('Accolade-DurumSeed');
$Accolade_OatSeed = iconic_get_product_id_by_sku('Accolade-OatSeed');
$Accolade_BarleySeed = iconic_get_product_id_by_sku('Accolade-BarleySeed');
$Accolade_FlaxSeed = iconic_get_product_id_by_sku('Accolade-FlaxSeed');
$Accolade_FallRyeSeed = iconic_get_product_id_by_sku('Accolade-FallRyeSeed');
$Accolade_CanarySeed = iconic_get_product_id_by_sku('Accolade-CanarySeed');
$Accolade_PeaSeed = iconic_get_product_id_by_sku('Accolade-PeaSeed');
$Accolade_LentilSeed = iconic_get_product_id_by_sku('Accolade-LentilSeed');
$VibranceQuattro_WheatSeed = iconic_get_product_id_by_sku('VibranceQuattro-WheatSeed');
$VibranceQuattro_DurumSeed = iconic_get_product_id_by_sku('VibranceQuattro-DurumSeed');
$VibranceQuattro_OatSeed = iconic_get_product_id_by_sku('VibranceQuattro-OatSeed');
$VibranceQuattro_BarleySeed = iconic_get_product_id_by_sku('VibranceQuattro-BarleySeed');
$VibranceQuattro_FlaxSeed = iconic_get_product_id_by_sku('VibranceQuattro-FlaxSeed');
$VibranceQuattro_FallRyeSeed = iconic_get_product_id_by_sku('VibranceQuattro-FallRyeSeed');
$VibranceQuattro_CanarySeed = iconic_get_product_id_by_sku('VibranceQuattro-CanarySeed');
$CruiserVibranceQuattro_WheatSeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-WheatSeed');
$CruiserVibranceQuattro_DurumSeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-DurumSeed');
$CruiserVibranceQuattro_OatSeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-OatSeed');
$CruiserVibranceQuattro_BarleySeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-BarleySeed');
$CruiserVibranceQuattro_FlaxSeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-FlaxSeed');
$CruiserVibranceQuattro_FallRyeSeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-FallRyeSeed');
$CruiserVibranceQuattro_CanarySeed = iconic_get_product_id_by_sku('CruiserVibranceQuattro-CanarySeed');
$VibranceMaxxRFC_PeaSeed = iconic_get_product_id_by_sku('VibranceMaxxRFC-PeaSeed');
$VibranceMaxxRFC_LentilSeed = iconic_get_product_id_by_sku('VibranceMaxxRFC-LentilSeed');
$InsurePulse_PeaSeed = iconic_get_product_id_by_sku('InsurePulse-PeaSeed');
$InsurePulse_LentilSeed = iconic_get_product_id_by_sku('InsurePulse-LentilSeed');
$InsureCereal_WheatSeed = iconic_get_product_id_by_sku('InsureCereal-WheatSeed');
$InsureCereal_DurumSeed = iconic_get_product_id_by_sku('InsureCereal-DurumSeed');
$InsureCereal_OatSeed = iconic_get_product_id_by_sku('InsureCereal-OatSeed');
$InsureCereal_BarleySeed = iconic_get_product_id_by_sku('InsureCereal-BarleySeed');
$InsureCereal_FlaxSeed = iconic_get_product_id_by_sku('InsureCereal-FlaxSeed');
$InsureCereal_FallRyeSeed = iconic_get_product_id_by_sku('InsureCereal-FallRyeSeed');
$InsureCereal_CanarySeed = iconic_get_product_id_by_sku('InsureCereal-CanarySeed');
$RaxilPro_WheatSeed = iconic_get_product_id_by_sku('RaxilPro-WheatSeed');
$RaxilPro_DurumSeed = iconic_get_product_id_by_sku('RaxilPro-DurumSeed');
$RaxilPro_OatSeed = iconic_get_product_id_by_sku('RaxilPro-OatSeed');
$RaxilPro_BarleySeed = iconic_get_product_id_by_sku('RaxilPro-BarleySeed');
$RaxilPro_FlaxSeed = iconic_get_product_id_by_sku('RaxilPro-FlaxSeed');
$RaxilPro_FallRyeSeed = iconic_get_product_id_by_sku('RaxilPro-FallRyeSeed');
$RaxilPro_CanarySeed = iconic_get_product_id_by_sku('RaxilPro-CanarySeed');
$RaxilProSS_WheatSeed = iconic_get_product_id_by_sku('RaxilProSS-WheatSeed');
$RaxilProSS_DurumSeed = iconic_get_product_id_by_sku('RaxilProSS-DurumSeed');
$RaxilProSS_OatSeed = iconic_get_product_id_by_sku('RaxilProSS-OatSeed');
$RaxilProSS_BarleySeed = iconic_get_product_id_by_sku('RaxilProSS-BarleySeed');
$RaxilProSS_FlaxSeed = iconic_get_product_id_by_sku('RaxilProSS-FlaxSeed');
$RaxilProSS_FallRyeSeed = iconic_get_product_id_by_sku('RaxilProSS-FallRyeSeed');
$RaxilProSS_CanarySeed = iconic_get_product_id_by_sku('RaxilProSS-CanarySeed');
$Trilex_PeaSeed = iconic_get_product_id_by_sku('Trilex-PeaSeed');
$Trilex_LentilSeed = iconic_get_product_id_by_sku('Trilex-LentilSeed');
/*
$wheat_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Wheat' data-product_sku='PrecedeC-WheatSeed' data-product-id='$PrecedeC_WheatSeed[0]' data-product-price='2.28'>Precede Cereal - Wheat (+ $2.28/bu)</option><option value='Action 5% - Wheat' data-product_sku='Action5-WheatSeed' data-product-id='$Action5_WheatSeed' data-product-price='2.20'>Action 5% - Wheat (+ $2.2/bu)</option><option value='Primer Zn - Wheat' data-product_sku='PrimerZn-WheatSeed' data-product-id='$PrimerZn_WheatSeed' data-product-price='2.28'>Primer Zn - Wheat (+ $2.28/bu)</option><option value='Primer Cu - Wheat' data-product_sku='PrimerCu-WheatSeed' data-product-id='$PrimerCu_WheatSeed' data-product-price='2.28'>Primer Cu - Wheat (+ $2.28/bu)</option><option value='Primer Mn - Wheat' data-product_sku='PrimerMn-WheatSeed' data-product-id='$PrimerMn_WheatSeed' data-product-price='2.28'>Primer Mn - Wheat (+ $2.28/bu)</option></select>";";
$wheat_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Wheat' data-product_sku='Accolade-WheatSeed' data-product-id='$Accolade_WheatSeed' data-product-price='1.75'>Accolade - Wheat (+ $1.75/bu)</option></select>";";;
$wheat_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Wheat' data-product_sku='VibranceQuattro-WheatSeed' data-product-id='$VibranceQuattro_WheatSeed' data-product-price='2.57'>Vibrance Quattro - Wheat (+ $2.57/bu)</option><option value='Cruiser Vibrance Quattro - Wheat' data-product_sku='CruiserVibranceQuattro-WheatSeed' data-product-id='$CruiserVibranceQuattro_WheatSeed' data-product-price='4.29'>Cruiser Vibrance Quattro - Wheat (+ $4.29/bu)</option><option value='Insure Cereal FX4 - Wheat' data-product_sku='InsureCereal-WheatSeed' data-product-id='$InsureCereal_WheatSeed' data-product-price='3.33'>Insure Cereal FX4 - Wheat (+ $3.33/bu)</option><option value='Raxil Pro - Wheat' data-product_sku='RaxilPro-WheatSeed' data-product-id='$RaxilPro_WheatSeed' data-product-price='2.79'>Raxil Pro - Wheat (+ $2.79/bu)</option><option value='Raxil Pro Stress Shield - Wheat' data-product_sku='RaxilProSS-WheatSeed' data-product-id='$RaxilProSS_WheatSeed' data-product-price='4.65'>Raxil Pro Stress Shield - Wheat (+ $4.65/bu)</option></select>";";

$barley_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Barley' data-product_sku='PrecedeC-BarleySeed' data-product-id='$PrecedeC_BarleySeed' data-product-price='1.83'>Precede Cereal - Barley  (+ $1.83/bu)</option><option value='Action 5% - Barley' data-product_sku='Action5-BarleySeed' data-product-id='$Action5_BarleySeed' data-product-price='1.75'>Action 5% - Barley  (+ $1.75/bu)</option><option value='Primer Zn - Barley' data-product_sku='PrimerZn-BarleySeed' data-product-id='$PrimerZn_BarleySeed' data-product-price='1.83'>Primer Zn - Barley  (+ $1.83/bu)</option><option value='Primer Cu - Barley' data-product_sku='PrimerCu-BarleySeed' data-product-id='$PrimerCu_BarleySeed' data-product-price='1.83'>Primer Cu - Barley  (+ $1.83/bu)</option><option value='Primer Mn - Barley' data-product_sku='PrimerMn-BarleySeed' data-product-id='$PrimerMn_BarleySeed' data-product-price='1.83'>Primer Mn - Barley  (+ $1.83/bu)</option></select>";";
$barley_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Barley' data-product_sku='Accolade-BarleySeed' data-product-id='$Accolade_BarleySeed' data-product-price='1.40'>Accolade - Barley  (+ $1.4/bu)</option></select>";";
$barley_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Barley' data-product_sku='VibranceQuattro-BarleySeed' data-product-id='$VibranceQuattro_BarleySeed' data-product-price='2.06'>Vibrance Quattro - Barley  (+ $2.06/bu)</option><option value='Cruiser Vibrance Quattro - Barley' data-product_sku='CruiserVibranceQuattro-BarleySeed' data-product-id='$CruiserVibranceQuattro_BarleySeed' data-product-price='3.44'>Cruiser Vibrance Quattro - Barley  (+ $3.44/bu)</option><option value='Insure Cereal FX4 - Barley' data-product_sku='InsureCereal-BarleySeed' data-product-id='$InsureCereal_BarleySeed' data-product-price='2.67'>Insure Cereal FX4 - Barley  (+ $2.67/bu)</option><option value='Raxil Pro - Barley' data-product_sku='RaxilPro-BarleySeed' data-product-id='$RaxilPro_BarleySeed' data-product-price='2.23'>Raxil Pro - Barley  (+ $2.23/bu)</option><option value='Raxil Pro Stress Shield - Barley' data-product_sku='RaxilProSS-BarleySeed' data-product-id='$RaxilProSS_BarleySeed' data-product-price='3.72'>Raxil Pro Stress Shield - Barley  (+ $3.72/bu)</option></select>";";

$oat_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Oat' data-product_sku='PrecedeC-OatSeed' data-product-id='$PrecedeC_OatSeed' data-product-price='1.30'>Precede Cereal - Oat  (+ $1.3/bu)</option><option value='Action 5% - Oat' data-product_sku='Action5-OatSeed' data-product-id='$Action5_OatSeed' data-product-price='1.25'>Action 5% - Oat (+ $1.25/bu)</option><option value='Primer Zn - Oat' data-product_sku='PrimerZn-OatSeed' data-product-id='$PrimerZn_OatSeed' data-product-price='1.30'>Primer Zn - Oat (+ $1.3/bu)</option><option value='Primer Cu - Oat' data-product_sku='PrimerCu-OatSeed' data-product-id='$PrimerCu_OatSeed' data-product-price='1.30'>Primer Cu - Oat (+ $1.3/bu)</option><option value='Primer Mn - Oat' data-product_sku='PrimerMn-OatSeed' data-product-id='$PrimerMn_OatSeed' data-product-price='1.30'>Primer Mn - Oat (+ $1.3/bu)</option></select>";";
$oat_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Oat' data-product_sku='Accolade-OatSeed' data-product-id='$Accolade_OatSeed' data-product-price='1.00'>Accolade - Oat (+ $1/bu)</option></select>";";
$oat_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Oat' data-product_sku='VibranceQuattro-OatSeed' data-product-id='$VibranceQuattro_OatSeed' data-product-price='1.45'>Vibrance Quattro - Oat (+ $1.45/bu)</option><option value='Cruiser Vibrance Quattro - Oat' data-product_sku='CruiserVibranceQuattro-OatSeed' data-product-id='$CruiserVibranceQuattro_OatSeed' data-product-price='2.43'>Cruiser Vibrance Quattro - Oat (+ $2.43/bu)</option><option value='Insure Cereal FX4 - Oat' data-product_sku='InsureCereal-OatSeed' data-product-id='$InsureCereal_OatSeed' data-product-price='1.90'>Insure Cereal FX4 - Oat (+ $1.9/bu)</option><option value='Raxil Pro - Oat' data-product_sku='RaxilPro-OatSeed' data-product-id='$RaxilPro_OatSeed' data-product-price='1.58'>Raxil Pro - Oat (+ $1.58/bu)</option><option value='Raxil Pro Stress Shield - Oat' data-product_sku='RaxilProSS-OatSeed' data-product-id='$RaxilProSS_OatSeed' data-product-price='2.63'>Raxil Pro Stress Shield - Oat (+ $2.63/bu)</option></select>";";

$durum_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Durum' data-product_sku='PrecedeC-DurumSeed' data-product-id='$PrecedeC_DurumSeed' data-product-price='2.28'>Precede Cereal - Durum  (+ $2.28/bu)</option><option value='Action 5% - Durum' data-product_sku='Action5-DurumSeed' data-product-id='$Action5_DurumSeed' data-product-price='2.20'>Action 5% - Durum  (+ $2.2/bu)</option><option value='Primer Zn - Durum' data-product_sku='PrimerZn-DurumSeed' data-product-id='$PrimerZn_DurumSeed' data-product-price='2.28'>Primer Zn - Durum  (+ $2.28/bu)</option><option value='Primer Cu - Durum' data-product_sku='PrimerCu-DurumSeed' data-product-id='$PrimerCu_DurumSeed' data-product-price='2.28'>Primer Cu - Durum  (+ $2.28/bu)</option><option value='Primer Mn - Durum' data-product_sku='PrimerMn-DurumSeed' data-product-id='$PrimerMn_DurumSeed' data-product-price='2.28'>Primer Mn - Durum  (+ $2.28/bu)</option></select>";";
$durum_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Durum' data-product_sku='Accolade-DurumSeed' data-product-id='$Accolade_DurumSeed' data-product-price='1.75'>Accolade - Durum  (+ $1.75/bu)</option></select>";";
$durum_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Durum' data-product_sku='VibranceQuattro-DurumSeed' data-product-id='$VibranceQuattro_DurumSeed' data-product-price='2.57'>Vibrance Quattro - Durum  (+ $2.57/bu)</option><option value='Cruiser Vibrance Quattro - Durum' data-product_sku='CruiserVibranceQuattro-DurumSeed' data-product-id='$CruiserVibranceQuattro_DurumSeed' data-product-price='4.29'>Cruiser Vibrance Quattro - Durum  (+ $4.29/bu)</option><option value='Insure Cereal FX4 - Durum' data-product_sku='InsureCereal-DurumSeed' data-product-id='$InsureCereal_DurumSeed' data-product-price='3.33'>Insure Cereal FX4 - Durum  (+ $3.33/bu)</option><option value='Raxil Pro - Durum' data-product_sku='RaxilPro-DurumSeed' data-product-id='$RaxilPro_DurumSeed' data-product-price='2.79'>Raxil Pro - Durum  (+ $2.79/bu)</option><option value='Raxil Pro Stress Shield - Durum' data-product_sku='RaxilProSS-DurumSeed' data-product-id='$RaxilProSS_DurumSeed' data-product-price='4.65'>Raxil Pro Stress Shield - Durum  (+ $4.65/bu)</option></select>";";

$flax_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Flax' data-product_sku='PrecedeC-FlaxSeed' data-product-id='$PrecedeC_FlaxSeed' data-product-price='2.14'>Precede Cereal - Flax (+ $2.14/bu)</option><option value='Action 5% - Flax' data-product_sku='Action5-FlaxSeed' data-product-id='$Action5_FlaxSeed' data-product-price='2.05'>Action 5% - Flax (+ $2.05/bu)</option><option value='Primer Zn - Flax' data-product_sku='PrimerZn-FlaxSeed' data-product-id='$PrimerZn_FlaxSeed' data-product-price='2.14'>Primer Zn - Flax (+ $2.14/bu)</option><option value='Primer Cu - Flax' data-product_sku='PrimerCu-FlaxSeed' data-product-id='$PrimerCu_FlaxSeed' data-product-price='2.14'>Primer Cu - Flax (+ $2.14/bu)</option><option value='Primer Mn - Flax' data-product_sku='PrimerMn-FlaxSeed' data-product-id='$PrimerMn_FlaxSeed' data-product-price='2.14'>Primer Mn - Flax (+ $2.14/bu)</option></select>";";
$flax_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Flax' data-product_sku='Accolade-FlaxSeed' data-product-id='$Accolade_FlaxSeed' data-product-price='1.64'>Accolade - Flax (+ $1.64/bu)</option></select>";";
$flax_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Flax' data-product_sku='VibranceQuattro-FlaxSeed' data-product-id='$VibranceQuattro_FlaxSeed' data-product-price='2.40'>Vibrance Quattro - Flax (+ $2.4/bu)</option><option value='Cruiser Vibrance Quattro - Flax' data-product_sku='CruiserVibranceQuattro-FlaxSeed' data-product-id='$CruiserVibranceQuattro_FlaxSeed' data-product-price='4.01'>Cruiser Vibrance Quattro - Flax (+ $4.01/bu)</option><option value='Insure Cereal FX4 - Flax' data-product_sku='InsureCereal-FlaxSeed' data-product-id='$InsureCereal_FlaxSeed' data-product-price='3.13'>Insure Cereal FX4 - Flax (+ $3.13/bu)</option><option value='Raxil Pro - Flax' data-product_sku='RaxilPro-FlaxSeed' data-product-id='$RaxilPro_FlaxSeed' data-product-price='2.60'>Raxil Pro - Flax (+ $2.6/bu)</option><option value='Raxil Pro Stress Shield - Flax' data-product_sku='RaxilProSS-FlaxSeed' data-product-id='$RaxilProSS_FlaxSeed' data-product-price='4.34'>Raxil Pro Stress Shield - Flax (+ $4.34/bu)</option></select>";";

$fallRye_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Fall Rye' data-product_sku='PrecedeC-FallRyeSeed' data-product-id='$PrecedeC_FallRyeSeed' data-product-price='2.14'>Precede Cereal - Fall Rye (+ $2.14/bu)</option><option value='Action 5% - Fall Rye' data-product_sku='Action5-FallRyeSeed' data-product-id='$Action5_FallRyeSeed' data-product-price='2.05'>Action 5% - Fall Rye (+ $2.05/bu)</option><option value='Primer Zn - Fall Rye' data-product_sku='PrimerZn-FallRyeSeed' data-product-id='$PrimerZn_FallRyeSeed' data-product-price='2.14'>Primer Zn - Fall Rye (+ $2.14/bu)</option><option value='Primer Cu - Fall Rye' data-product_sku='PrimerCu-FallRyeSeed' data-product-id='$PrimerCu_FallRyeSeed' data-product-price='2.14'>Primer Cu - Fall Rye (+ $2.14/bu)</option><option value='Primer Mn - Fall Rye' data-product_sku='PrimerMn-FallRyeSeed' data-product-id='$PrimerMn_FallRyeSeed' data-product-price='2.14'>Primer Mn - Fall Rye (+ $2.14/bu)</option></select>";";
$fallRye_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Fall Rye' data-product_sku='Accolade-FallRyeSeed' data-product-id='$Accolade_FallRyeSeed' data-product-price='1.64'>Accolade - Fall Rye (+ $1.64/bu)</option></select>";";
$fallRye_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Fall Rye' data-product_sku='VibranceQuattro-FallRyeSeed' data-product-id='$VibranceQuattro_FallRyeSeed' data-product-price='2.40'>Vibrance Quattro - Fall Rye (+ $2.4/bu)</option><option value='Cruiser Vibrance Quattro - Fall Rye' data-product_sku='CruiserVibranceQuattro-FallRyeSeed' data-product-id='$CruiserVibranceQuattro_FallRyeSeed' data-product-price='9.00'>Cruiser Vibrance Quattro - Fall Rye (+ $9/bu)</option><option value='Insure Cereal FX4 - Fall Rye' data-product_sku='InsureCereal-FallRyeSeed' data-product-id='$InsureCereal_FallRyeSeed' data-product-price='3.13'>Insure Cereal FX4 - Fall Rye (+ $3.13/bu)</option><option value='Raxil Pro - Fall Rye' data-product_sku='RaxilPro-FallRyeSeed' data-product-id='$RaxilPro_FallRyeSeed' data-product-price='2.60'>Raxil Pro - Fall Rye (+ $2.6/bu)</option><option value='Raxil Pro Stress Shield - Fall Rye' data-product_sku='RaxilProSS-FallRyeSeed' data-product-id='$RaxilProSS_FallRyeSeed' data-product-price='4.34'>Raxil Pro Stress Shield - Fall Rye (+ $4.34/bu)</option></select>";";

$canary_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Cereal - Canary' data-product_sku='PrecedeC-CanarySeed' data-product-id='$PrecedeC_CanarySeed' data-product-price='1.90'>Precede Cereal - Canary (+ $1.9/bu)</option><option value='Action 5% - Canary' data-product_sku='Action5-CanarySeed' data-product-id='$Action5_CanarySeed' data-product-price='1.83'>Action 5% - Canary  (+ $1.83/bu)</option><option value='Primer Zn - Canary' data-product_sku='PrimerZn-CanarySeed' data-product-id='$PrimerZn_CanarySeed' data-product-price='1.91'>Primer Zn - Canary  (+ $1.91/bu)</option><option value='Primer Cu - Canary' data-product_sku='PrimerCu-CanarySeed' data-product-id='$PrimerCu_CanarySeed' data-product-price='1.91'>Primer Cu - Canary  (+ $1.91/bu)</option><option value='Primer Mn - Canary' data-product_sku='PrimerMn-CanarySeed' data-product-id='$PrimerMn_CanarySeed' data-product-price='1.91'>Primer Mn - Canary (+ $1.91/bu)</option></select>";";
$canary_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Accolade - Canary' data-product_sku='Accolade-CanarySeed' data-product-id='$Accolade_CanarySeed' data-product-price='1.47'>Accolade - Canary  (+ $1.47/bu)</option></select>";";
$canary_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Quattro - Canary' data-product_sku='VibranceQuattro-CanarySeed' data-product-id='$VibranceQuattro_CanarySeed' data-product-price='2.15'>Vibrance Quattro - Canary  (+ $2.15/bu)</option><option value='Cruiser Vibrance Quattro - Canary' data-product_sku='CruiserVibranceQuattro-CanarySeed' data-product-id='$CruiserVibranceQuattro_CanarySeed' data-product-price='3.59'>Cruiser Vibrance Quattro - Canary  (+ $3.59/bu)</option><option value='Insure Cereal FX4 - Canary' data-product_sku='InsureCereal-CanarySeed' data-product-id='$InsureCereal_CanarySeed' data-product-price='2.78'>Insure Cereal FX4 - Canary  (+ $2.78/bu)</option><option value='Raxil Pro - Canary' data-product_sku='RaxilPro-CanarySeed' data-product-id='$RaxilPro_CanarySeed' data-product-price='2.33'>Raxil Pro - Canary  (+ $2.33/bu)</option><option value='Raxil Pro Stress Shield - Canary' data-product_sku='RaxilProSS-CanarySeed' data-product-id='$RaxilProSS_CanarySeed' data-product-price='3.89'>Raxil Pro Stress Shield - Canary (+ $3.89/bu)</option></select>";";

$pea_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Pulse - Pea' data-product_sku='PrecedeP-PeaSeed' data-product-id='$PrecedeP_PeaSeed' data-product-price='2.28'>Precede Pulse - Pea (+ $2.28/bu)</option><option value='BioForge Advance - Pea' data-product_sku='BioForge-PeaSeed' data-product-id='$BioForge_PeaSeed' data-product-price='2.89'>BioForge Advance - Pea (+ $2.89/bu)</option><option value='Pulse Primer - Pea' data-product_sku='PulsePrimer-PeaSeed' data-product-id='$PulsePrimer_PeaSeed' data-product-price='2.28'>Pulse Primer - Pea (+ $2.28/bu)</option><option value='Pulse Pak - Pea' data-product_sku='PulsePak-PeaSeed' data-product-id='$PulsePak_PeaSeed' data-product-price='4.56'>Pulse Pak - Pea (+ $4.56/bu)</option></select>";";
$pea_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Tag Team LCO Liquid - Pea' data-product_sku='TagTeamLCO-PeaSeed' data-product-id='$TagTeamLCO_PeaSeed' data-product-price='1.20'>Tag Team LCO Liquid - Pea (+ $1.2/bu)</option><option value='Cell Tech Liquid - Pea' data-product_sku='CellTech-PeaSeed' data-product-id='$CellTech_PeaSeed' data-product-price='1.13'>Cell Tech Liquid - Pea (+ $1.13/bu)</option><option value='Nodulator Liquid - Pea' data-product_sku='Nodulator-PeaSeed' data-product-id='$Nodulator_PeaSeed' data-product-price='2.50'>Nodulator Liquid - Pea (+ $2.5/bu)</option><option value='Accolade - Pea' data-product_sku='Accolade-PeaSeed' data-product-id='$Accolade_PeaSeed' data-product-price='1.75'>Accolade - Pea (+ $1.75/bu)</option></select>";";
$pea_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Maxx RFC - Pea' data-product_sku='VibranceMaxxRFC-PeaSeed' data-product-id='$VibranceMaxxRFC_PeaSeed' data-product-price='4.03'>Vibrance Maxx RFC - Pea (+ $4.03/bu)</option><option value='Insure Pulse - Pea' data-product_sku='InsurePulse-PeaSeed' data-product-id='$InsurePulse_PeaSeed' data-product-price='5.58'>Insure Pulse - Pea (+ $5.58/bu)</option><option value='Trilex - Pea' data-product_sku='Trilex-PeaSeed' data-product-id='$Trilex_PeaSeed' data-product-price='4.48'>Trilex - Pea (+ $4.48/bu)</option></select>";";

$lentil_primer="<select name='primer'><option value='none'>None</option><option value='none'>None</option><option value='Precede Pulse - Lentil' data-product_sku='PrecedeP-LentilSeed' data-product-id='$PrecedeP_LentilSeed' data-product-price='2.28'>Precede Pulse - Lentil  (+ $2.28/bu)</option><option value='BioForge Advance - Lentil' data-product_sku='BioForge-LentilSeed' data-product-id='$BioForge_LentilSeed' data-product-price='2.89'>BioForge Advance - Lentil  (+ $2.89/bu)</option><option value='Pulse Primer - Lentil' data-product_sku='PulsePrimer-LentilSeed' data-product-id='$PulsePrimer_LentilSeed' data-product-price='2.28'>Pulse Primer - Lentil  (+ $2.28/bu)</option><option value='Pulse Pak - Lentil' data-product_sku='PulsePak-LentilSeed' data-product-id='$PulsePak_LentilSeed' data-product-price='4.56'>Pulse Pak - Lentil  (+ $4.56/bu)</option></select>";";
$lentil_inoculant="<select name='inoculant'><option value='none'>None</option><option value='none'>None</option><option value='Tag Team LCO Liquid - Lentil' data-product_sku='TagTeamLCO-LentilSeed' data-product-id='$TagTeamLCO_LentilSeed' data-product-price='1.20'>Tag Team LCO Liquid - Lentil  (+ $1.2/bu)</option><option value='Cell Tech Liquid - Lentil' data-product_sku='CellTech-LentilSeed' data-product-id='$CellTech_LentilSeed' data-product-price='1.13'>Cell Tech Liquid - Lentil  (+ $1.13/bu)</option><option value='Nodulator Liquid - Lentil' data-product_sku='Nodulator-LentilSeed' data-product-id='$Nodulator_LentilSeed' data-product-price='2.50'>Nodulator Liquid - Lentil  (+ $2.5/bu)</option><option value='Accolade - Lentil' data-product_sku='Accolade-LentilSeed' data-product-id='$Accolade_LentilSeed' data-product-price='1.75'>Accolade - Lentil  (+ $1.75/bu)</option></select>";";
$lentil_treatment="<select name='treatment'><option value='none'>None</option><option value='none'>None</option><option value='Vibrance Maxx RFC - Lentil' data-product_sku='VibranceMaxxRFC-LentilSeed' data-product-id='$VibranceMaxxRFC_LentilSeed' data-product-price='4.03'>Vibrance Maxx RFC - Lentil  (+ $4.03/bu)</option><option value='Insure Pulse - Lentil' data-product_sku='InsurePulse-LentilSeed' data-product-id='$InsurePulse_LentilSeed' data-product-price='5.58'>Insure Pulse - Lentil  (+ $5.58/bu)</option><option value='Trilex - Lentil' data-product_sku='Trilex-LentilSeed' data-product-id='$Trilex_LentilSeed' data-product-price='4.48'>Trilex - Lentil  (+ $4.48/bu)</option></select>";";
*/

$wheat_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Wheat' data-product_sku='PrecedeC-WheatSeed' data-product-id='$PrecedeC_WheatSeed[0]' data-product-price='2.28'>Precede Cereal - Wheat $PrecedeC_WheatSeed[1] $$PrecedeC_WheatSeed[2] (+ $2.28/bu)</option><option value='Action 5% - Wheat' data-product_sku='Action5-WheatSeed' data-product-id='$Action5_WheatSeed' data-product-price='2.20'>Action 5% - Wheat (+ $2.2/bu)</option></select>";
$wheat_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Wheat' data-product_sku='Accolade-WheatSeed' data-product-id='$Accolade_WheatSeed' data-product-price='1.75'>Accolade - Wheat (+ $1.75/bu)</option></select>";
$wheat_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Wheat' data-product_sku='VibranceQuattro-WheatSeed' data-product-id='$VibranceQuattro_WheatSeed' data-product-price='2.57'>Vibrance Quattro - Wheat (+ $2.57/bu)</option><option value='Cruiser Vibrance Quattro - Wheat' data-product_sku='CruiserVibranceQuattro-WheatSeed' data-product-id='$CruiserVibranceQuattro_WheatSeed' data-product-price='4.29'>Cruiser Vibrance Quattro - Wheat (+ $4.29/bu)</option><option value='Insure Cereal FX4 - Wheat' data-product_sku='InsureCereal-WheatSeed' data-product-id='$InsureCereal_WheatSeed' data-product-price='3.33'>Insure Cereal FX4 - Wheat (+ $3.33/bu)</option><option value='Raxil Pro - Wheat' data-product_sku='RaxilPro-WheatSeed' data-product-id='$RaxilPro_WheatSeed' data-product-price='2.79'>Raxil Pro - Wheat (+ $2.79/bu)</option><option value='Raxil Pro Stress Shield - Wheat' data-product_sku='RaxilProSS-WheatSeed' data-product-id='$RaxilProSS_WheatSeed' data-product-price='4.65'>Raxil Pro Stress Shield - Wheat (+ $4.65/bu)</option></select>";

$barley_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Barley' data-product_sku='PrecedeC-BarleySeed' data-product-id='$PrecedeC_BarleySeed' data-product-price='1.83'>Precede Cereal - Barley  (+ $1.83/bu)</option><option value='Action 5% - Barley' data-product_sku='Action5-BarleySeed' data-product-id='$Action5_BarleySeed' data-product-price='1.75'>Action 5% - Barley  (+ $1.75/bu)</option></select>";
$barley_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Barley' data-product_sku='Accolade-BarleySeed' data-product-id='$Accolade_BarleySeed' data-product-price='1.40'>Accolade - Barley  (+ $1.4/bu)</option></select>";
$barley_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Barley' data-product_sku='VibranceQuattro-BarleySeed' data-product-id='$VibranceQuattro_BarleySeed' data-product-price='2.06'>Vibrance Quattro - Barley  (+ $2.06/bu)</option><option value='Cruiser Vibrance Quattro - Barley' data-product_sku='CruiserVibranceQuattro-BarleySeed' data-product-id='$CruiserVibranceQuattro_BarleySeed' data-product-price='3.44'>Cruiser Vibrance Quattro - Barley  (+ $3.44/bu)</option><option value='Insure Cereal FX4 - Barley' data-product_sku='InsureCereal-BarleySeed' data-product-id='$InsureCereal_BarleySeed' data-product-price='2.67'>Insure Cereal FX4 - Barley  (+ $2.67/bu)</option><option value='Raxil Pro - Barley' data-product_sku='RaxilPro-BarleySeed' data-product-id='$RaxilPro_BarleySeed' data-product-price='2.23'>Raxil Pro - Barley  (+ $2.23/bu)</option><option value='Raxil Pro Stress Shield - Barley' data-product_sku='RaxilProSS-BarleySeed' data-product-id='$RaxilProSS_BarleySeed' data-product-price='3.72'>Raxil Pro Stress Shield - Barley  (+ $3.72/bu)</option></select>";

$oat_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Oat' data-product_sku='PrecedeC-OatSeed' data-product-id='$PrecedeC_OatSeed' data-product-price='1.30'>Precede Cereal - Oat  (+ $1.3/bu)</option><option value='Action 5% - Oat' data-product_sku='Action5-OatSeed' data-product-id='$Action5_OatSeed' data-product-price='1.25'>Action 5% - Oat (+ $1.25/bu)</option></select>";
$oat_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Oat' data-product_sku='Accolade-OatSeed' data-product-id='$Accolade_OatSeed' data-product-price='1.00'>Accolade - Oat (+ $1/bu)</option></select>";
$oat_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Oat' data-product_sku='VibranceQuattro-OatSeed' data-product-id='$VibranceQuattro_OatSeed' data-product-price='1.45'>Vibrance Quattro - Oat (+ $1.45/bu)</option><option value='Cruiser Vibrance Quattro - Oat' data-product_sku='CruiserVibranceQuattro-OatSeed' data-product-id='$CruiserVibranceQuattro_OatSeed' data-product-price='2.43'>Cruiser Vibrance Quattro - Oat (+ $2.43/bu)</option><option value='Insure Cereal FX4 - Oat' data-product_sku='InsureCereal-OatSeed' data-product-id='$InsureCereal_OatSeed' data-product-price='1.90'>Insure Cereal FX4 - Oat (+ $1.9/bu)</option><option value='Raxil Pro - Oat' data-product_sku='RaxilPro-OatSeed' data-product-id='$RaxilPro_OatSeed' data-product-price='1.58'>Raxil Pro - Oat (+ $1.58/bu)</option><option value='Raxil Pro Stress Shield - Oat' data-product_sku='RaxilProSS-OatSeed' data-product-id='$RaxilProSS_OatSeed' data-product-price='2.63'>Raxil Pro Stress Shield - Oat (+ $2.63/bu)</option></select>";

$durum_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Durum' data-product_sku='PrecedeC-DurumSeed' data-product-id='$PrecedeC_DurumSeed' data-product-price='2.28'>Precede Cereal - Durum  (+ $2.28/bu)</option><option value='Action 5% - Durum' data-product_sku='Action5-DurumSeed' data-product-id='$Action5_DurumSeed' data-product-price='2.20'>Action 5% - Durum  (+ $2.2/bu)</option></select>";
$durum_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Durum' data-product_sku='Accolade-DurumSeed' data-product-id='$Accolade_DurumSeed' data-product-price='1.75'>Accolade - Durum  (+ $1.75/bu)</option></select>";
$durum_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Durum' data-product_sku='VibranceQuattro-DurumSeed' data-product-id='$VibranceQuattro_DurumSeed' data-product-price='2.57'>Vibrance Quattro - Durum  (+ $2.57/bu)</option><option value='Cruiser Vibrance Quattro - Durum' data-product_sku='CruiserVibranceQuattro-DurumSeed' data-product-id='$CruiserVibranceQuattro_DurumSeed' data-product-price='4.29'>Cruiser Vibrance Quattro - Durum  (+ $4.29/bu)</option><option value='Insure Cereal FX4 - Durum' data-product_sku='InsureCereal-DurumSeed' data-product-id='$InsureCereal_DurumSeed' data-product-price='3.33'>Insure Cereal FX4 - Durum  (+ $3.33/bu)</option><option value='Raxil Pro - Durum' data-product_sku='RaxilPro-DurumSeed' data-product-id='$RaxilPro_DurumSeed' data-product-price='2.79'>Raxil Pro - Durum  (+ $2.79/bu)</option><option value='Raxil Pro Stress Shield - Durum' data-product_sku='RaxilProSS-DurumSeed' data-product-id='$RaxilProSS_DurumSeed' data-product-price='4.65'>Raxil Pro Stress Shield - Durum  (+ $4.65/bu)</option></select>";

$flax_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Flax' data-product_sku='PrecedeC-FlaxSeed' data-product-id='$PrecedeC_FlaxSeed' data-product-price='2.14'>Precede Cereal - Flax (+ $2.14/bu)</option><option value='Action 5% - Flax' data-product_sku='Action5-FlaxSeed' data-product-id='$Action5_FlaxSeed' data-product-price='2.05'>Action 5% - Flax (+ $2.05/bu)</option></select>";
$flax_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Flax' data-product_sku='Accolade-FlaxSeed' data-product-id='$Accolade_FlaxSeed' data-product-price='1.64'>Accolade - Flax (+ $1.64/bu)</option></select>";
$flax_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Flax' data-product_sku='VibranceQuattro-FlaxSeed' data-product-id='$VibranceQuattro_FlaxSeed' data-product-price='2.40'>Vibrance Quattro - Flax (+ $2.4/bu)</option><option value='Cruiser Vibrance Quattro - Flax' data-product_sku='CruiserVibranceQuattro-FlaxSeed' data-product-id='$CruiserVibranceQuattro_FlaxSeed' data-product-price='4.01'>Cruiser Vibrance Quattro - Flax (+ $4.01/bu)</option><option value='Insure Cereal FX4 - Flax' data-product_sku='InsureCereal-FlaxSeed' data-product-id='$InsureCereal_FlaxSeed' data-product-price='3.13'>Insure Cereal FX4 - Flax (+ $3.13/bu)</option><option value='Raxil Pro - Flax' data-product_sku='RaxilPro-FlaxSeed' data-product-id='$RaxilPro_FlaxSeed' data-product-price='2.60'>Raxil Pro - Flax (+ $2.6/bu)</option><option value='Raxil Pro Stress Shield - Flax' data-product_sku='RaxilProSS-FlaxSeed' data-product-id='$RaxilProSS_FlaxSeed' data-product-price='4.34'>Raxil Pro Stress Shield - Flax (+ $4.34/bu)</option></select>";

$fallRye_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Fall Rye' data-product_sku='PrecedeC-FallRyeSeed' data-product-id='$PrecedeC_FallRyeSeed' data-product-price='2.14'>Precede Cereal - Fall Rye (+ $2.14/bu)</option><option value='Action 5% - Fall Rye' data-product_sku='Action5-FallRyeSeed' data-product-id='$Action5_FallRyeSeed' data-product-price='2.05'>Action 5% - Fall Rye (+ $2.05/bu)</option></select>";
$fallRye_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Fall Rye' data-product_sku='Accolade-FallRyeSeed' data-product-id='$Accolade_FallRyeSeed' data-product-price='1.64'>Accolade - Fall Rye (+ $1.64/bu)</option></select>";
$fallRye_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Fall Rye' data-product_sku='VibranceQuattro-FallRyeSeed' data-product-id='$VibranceQuattro_FallRyeSeed' data-product-price='2.40'>Vibrance Quattro - Fall Rye (+ $2.4/bu)</option><option value='Cruiser Vibrance Quattro - Fall Rye' data-product_sku='CruiserVibranceQuattro-FallRyeSeed' data-product-id='$CruiserVibranceQuattro_FallRyeSeed' data-product-price='9.00'>Cruiser Vibrance Quattro - Fall Rye (+ $9/bu)</option><option value='Insure Cereal FX4 - Fall Rye' data-product_sku='InsureCereal-FallRyeSeed' data-product-id='$InsureCereal_FallRyeSeed' data-product-price='3.13'>Insure Cereal FX4 - Fall Rye (+ $3.13/bu)</option><option value='Raxil Pro - Fall Rye' data-product_sku='RaxilPro-FallRyeSeed' data-product-id='$RaxilPro_FallRyeSeed' data-product-price='2.60'>Raxil Pro - Fall Rye (+ $2.6/bu)</option><option value='Raxil Pro Stress Shield - Fall Rye' data-product_sku='RaxilProSS-FallRyeSeed' data-product-id='$RaxilProSS_FallRyeSeed' data-product-price='4.34'>Raxil Pro Stress Shield - Fall Rye (+ $4.34/bu)</option></select>";

$canary_primer="<select name='primer'><option value='none'>None</option><option value='Precede Cereal - Canary' data-product_sku='PrecedeC-CanarySeed' data-product-id='$PrecedeC_CanarySeed' data-product-price='1.90'>Precede Cereal - Canary (+ $1.9/bu)</option><option value='Action 5% - Canary' data-product_sku='Action5-CanarySeed' data-product-id='$Action5_CanarySeed' data-product-price='1.83'>Action 5% - Canary  (+ $1.83/bu)</option></select>";
$canary_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Accolade - Canary' data-product_sku='Accolade-CanarySeed' data-product-id='$Accolade_CanarySeed' data-product-price='1.47'>Accolade - Canary  (+ $1.47/bu)</option></select>";
$canary_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Quattro - Canary' data-product_sku='VibranceQuattro-CanarySeed' data-product-id='$VibranceQuattro_CanarySeed' data-product-price='2.15'>Vibrance Quattro - Canary  (+ $2.15/bu)</option><option value='Cruiser Vibrance Quattro - Canary' data-product_sku='CruiserVibranceQuattro-CanarySeed' data-product-id='$CruiserVibranceQuattro_CanarySeed' data-product-price='3.59'>Cruiser Vibrance Quattro - Canary  (+ $3.59/bu)</option><option value='Insure Cereal FX4 - Canary' data-product_sku='InsureCereal-CanarySeed' data-product-id='$InsureCereal_CanarySeed' data-product-price='2.78'>Insure Cereal FX4 - Canary  (+ $2.78/bu)</option><option value='Raxil Pro - Canary' data-product_sku='RaxilPro-CanarySeed' data-product-id='$RaxilPro_CanarySeed' data-product-price='2.33'>Raxil Pro - Canary  (+ $2.33/bu)</option><option value='Raxil Pro Stress Shield - Canary' data-product_sku='RaxilProSS-CanarySeed' data-product-id='$RaxilProSS_CanarySeed' data-product-price='3.89'>Raxil Pro Stress Shield - Canary (+ $3.89/bu)</option></select>";

$pea_primer="<select name='primer'><option value='none'>None</option><option value='Precede Pulse - Pea' data-product_sku='PrecedeP-PeaSeed' data-product-id='$PrecedeP_PeaSeed' data-product-price='2.28'>Precede Pulse - Pea (+ $2.28/bu)</option><option value='BioForge Advance - Pea' data-product_sku='BioForge-PeaSeed' data-product-id='$BioForge_PeaSeed' data-product-price='2.89'>BioForge Advance - Pea (+ $2.89/bu)</option><option value='Pulse Pak - Pea' data-product_sku='PulsePak-PeaSeed' data-product-id='$PulsePak_PeaSeed' data-product-price='4.56'>Pulse Pak - Pea (+ $4.56/bu)</option></select>";
$pea_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Tag Team LCO Liquid - Pea' data-product_sku='TagTeamLCO-PeaSeed' data-product-id='$TagTeamLCO_PeaSeed' data-product-price='1.20'>Tag Team LCO Liquid - Pea (+ $1.2/bu)</option><option value='Cell Tech Liquid - Pea' data-product_sku='CellTech-PeaSeed' data-product-id='$CellTech_PeaSeed' data-product-price='1.13'>Cell Tech Liquid - Pea (+ $1.13/bu)</option><option value='Nodulator Liquid - Pea' data-product_sku='Nodulator-PeaSeed' data-product-id='$Nodulator_PeaSeed' data-product-price='2.50'>Nodulator Liquid - Pea (+ $2.5/bu)</option><option value='Accolade - Pea' data-product_sku='Accolade-PeaSeed' data-product-id='$Accolade_PeaSeed' data-product-price='1.75'>Accolade - Pea (+ $1.75/bu)</option></select>";
$pea_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Maxx RFC - Pea' data-product_sku='VibranceMaxxRFC-PeaSeed' data-product-id='$VibranceMaxxRFC_PeaSeed' data-product-price='4.03'>Vibrance Maxx RFC - Pea (+ $4.03/bu)</option><option value='Insure Pulse - Pea' data-product_sku='InsurePulse-PeaSeed' data-product-id='$InsurePulse_PeaSeed' data-product-price='5.58'>Insure Pulse - Pea (+ $5.58/bu)</option><option value='Trilex - Pea' data-product_sku='Trilex-PeaSeed' data-product-id='$Trilex_PeaSeed' data-product-price='4.48'>Trilex - Pea (+ $4.48/bu)</option></select>";

$lentil_primer="<select name='primer'><option value='none'>None</option><option value='Precede Pulse - Lentil' data-product_sku='PrecedeP-LentilSeed' data-product-id='$PrecedeP_LentilSeed' data-product-price='2.28'>Precede Pulse - Lentil  (+ $2.28/bu)</option><option value='BioForge Advance - Lentil' data-product_sku='BioForge-LentilSeed' data-product-id='$BioForge_LentilSeed' data-product-price='2.89'>BioForge Advance - Lentil  (+ $2.89/bu)</option><option value='Pulse Pak - Lentil' data-product_sku='PulsePak-LentilSeed' data-product-id='$PulsePak_LentilSeed' data-product-price='4.56'>Pulse Pak - Lentil  (+ $4.56/bu)</option></select>";
$lentil_inoculant="<select name='inoculant'><option value='none'>None</option><option value='Tag Team LCO Liquid - Lentil' data-product_sku='TagTeamLCO-LentilSeed' data-product-id='$TagTeamLCO_LentilSeed' data-product-price='1.20'>Tag Team LCO Liquid - Lentil  (+ $1.2/bu)</option><option value='Cell Tech Liquid - Lentil' data-product_sku='CellTech-LentilSeed' data-product-id='$CellTech_LentilSeed' data-product-price='1.13'>Cell Tech Liquid - Lentil  (+ $1.13/bu)</option><option value='Nodulator Liquid - Lentil' data-product_sku='Nodulator-LentilSeed' data-product-id='$Nodulator_LentilSeed' data-product-price='2.50'>Nodulator Liquid - Lentil  (+ $2.5/bu)</option><option value='Accolade - Lentil' data-product_sku='Accolade-LentilSeed' data-product-id='$Accolade_LentilSeed' data-product-price='1.75'>Accolade - Lentil  (+ $1.75/bu)</option></select>";
$lentil_treatment="<select name='treatment'><option value='none'>None</option><option value='Vibrance Maxx RFC - Lentil' data-product_sku='VibranceMaxxRFC-LentilSeed' data-product-id='$VibranceMaxxRFC_LentilSeed' data-product-price='4.03'>Vibrance Maxx RFC - Lentil  (+ $4.03/bu)</option><option value='Insure Pulse - Lentil' data-product_sku='InsurePulse-LentilSeed' data-product-id='$InsurePulse_LentilSeed' data-product-price='5.58'>Insure Pulse - Lentil  (+ $5.58/bu)</option><option value='Trilex - Lentil' data-product_sku='Trilex-LentilSeed' data-product-id='$Trilex_LentilSeed' data-product-price='4.48'>Trilex - Lentil  (+ $4.48/bu)</option></select>";

?>
